spring.application.name=ATTENDANCE-SERVICE
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group
spring.kafka.consumer.group-id=attendance-group
spring.kafka.consumer.auto-offset-reset=earliest

# ? Use ErrorHandlingDeserializer (MANDATORY)
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# ? Tell Kafka what object to deserialize INTO
spring.kafka.consumer.properties.spring.json.value.default.type=com.hrms.attendance_service.dto.LeaveApprovedEvent

# Trust packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*

